[package]
name = "sp_backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "sp_backend"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "1"
nakamoto = { git = "https://github.com/cygnet3/nakamoto", branch = "master" }
sp_client = { git = "https://github.com/cygnet3/sp-backend", branch = "master"}
lazy_static = "1.4"
electrum-client = { git = "https://github.com/cygnet3/rust-electrum-client", branch = "sp_tweaks" }
anyhow = "1.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
once_cell = "1.18.0"
bip39 = { version = "2.0.0", features = ["rand"] }
hex = { version = "0.4.3", features = ["serde"] }
serde_with = "3.6.0"
log = "0.4.20"
simplelog = "0.12.1"
bitcoin = { version = "0.31.1", features = ["serde", "rand", "base64"] }
reqwest = "0.12.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
pushtx = { git = "https://github.com/cygnet3/pushtx", branch = "signet-peers" }
